{% set data = load_setup_py_data() %}

package:
  name: carculator
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
  run:
    - scipy
    - pyprind
    - pandas
    - xarray<0.18
    - numpy
    - klausen
    - xlrd
    - pytest
    - numexpr
    - bw2io>0.8.0
    - pycountry
    - wurst

test:
  imports:
    - carculator

about:
  home: https://github.com/romainsacchi/carculator
  license: BSD License
  summary: 'A parameterized Python model to calculate the energy consumption and life cycle assessment of cars'
license_family: BSD